### ISSUE TITLE
Change 'Attribute' to 'Field'

### ISSUE THREAD

**Issue by ColtonKnopik** [hbarton2/cscd350-f24-TeamNull#110]
Field listed in help as attribute, replace all instances of the word 'attribute' with field in our program.

![FieldtoAttribute](https://github.com/user-attachments/assets/6bea04e8-f3d1-4c01-af90-93fb6770ee36)

**Comment by sMooreEWU** [comment]
I fixed this in my most recent merge. It now displays properly
