### ISSUE TITLE
Rename Method with no parameters

### ISSUE THREAD

**Issue by ColtonKnopik** [hbarton2/cscd350-f24-TeamNull#112]
It is not easy to rename a method that has no parameters, because parameters is a required field in our "rmn" (rename method). Change so if no parameters are entered, method is assumed to have no parameters and can be renamed.

![RenameMethod](https://github.com/user-attachments/assets/fed27db1-5ec1-4c22-a2b4-44309a6a71b3)

**Comment by ColtonKnopik** [comment]
This bug is here because there is no check for if parameters is blank in the renameMethod method. To fix we must add a check if the parameter section was left blank ("") then pass parameter in as "". The larger problem is that methods can only have one parameter and it is stored as a string.

**Comment by steeley21** [comment]
FIXED!! :)
