### ISSUE TITLE
Scenario: Altering Methods (ETE: 3-4 hours)

### ISSUE THREAD

**Issue by Delinquent-Pointer** [hbarton2/cscd350-f24-TeamNull#12]
# Scenarios and Features

### Scenario: Altering Methods (ETE: 3-4 hours)
**Feature**: Alter a Method of a Class

- **As a user**,  
  **I want to** alter the methods of a class,  
  **So that** I can update the function’s purpose.

#### Steps:
1. **Given** that I am in the Menu,
2. **When** I want to alter a method,
3. **Then** I should be required to input a valid class name and one of its valid methods,
4. **Then** I should be required to input the desired attribute(s) I want to change,
5. **Then** I should be required to input a valid value to change the attribute to,
6. **Then** I should be returned back to the Menu.

**Comment by ColtonKnopik** [comment]
I am unsure what attributes this is referring to. We already have implemented the ability to change a method's name and a method's parameters. The rubric does not mention anything about needing to change attributes of a method.

**Comment by Delinquent-Pointer** [comment]
v1.1.60 addressed
