### ISSUE TITLE
Quality of life function

### ISSUE THREAD

**Issue by danishwahidi** [hbarton2/cscd350-f24-TeamNull#123]
When the application opens swap focus the java fx window.
Fix the typo on help.

stage.toFront();
scene.requestFocus();
stage.setAlwaysOnTop(true);

**Comment by danishwahidi** [comment]
Added below code in AppStart  class right above primaryStage.getScene(scene); line.
primaryStage.toFront(); // to view window in front of all other windows, when user opens the GUI.

**Comment by Delinquent-Pointer** [comment]
v2.2.73 Issue #123 exit now a command
