### ISSUE TITLE
Separate print statements out of functions

### ISSUE THREAD

**Issue by steeley21** [hbarton2/cscd350-f24-TeamNull#161]

**Comment by ColtonKnopik** [comment]
Print statements in the functions class should be removed out of all methods and placed in a separate display class. 

for example createClass(){

//create class logic
print("class created"); <- remove this and place it in a new class 'Display'
}

//Display Class

createClassPrints(){
print("classcreated");
//any other prints to CLI or GUI
}

**Comment by ColtonKnopik** [comment]
Print statements will stay in the functions
