### ISSUE TITLE
Undo/Redo GUI

### ISSUE THREAD

**Issue by ColtonKnopik** [hbarton2/cscd350-f24-TeamNull#176]
Create two small buttons,
one with a curved arrow pointing to the left (undo)
one with the same curved arrow pointing right (redo)

These buttons will simply call the respective method in our functions class.
These buttons will use the already created undo/redo code for the CLI.

Scenario: Undo in GUI Mode

Given
I have performed an action in GUI mode,
•
When
I select the option to undo,
•
Then
the last action I performed should be reverted.

Scenario: Redo in GUI Mode

•
Given
I have undone an action in GUI mode,
•
When
I select the option to redo,
•
Then
the previously undone action should be reapplied.

**Comment by danishwahidi** [comment]
Uno / Redo functionality is working from GUI. It shows confirmation in CLI.
Still does not show confirmation to the user on GUI. 

Will open new issue to work on Undo / Redo confirmation for GUI.
