### ISSUE TITLE
Scenario: List Classes (ETE: 4-5 hours)

### ISSUE THREAD

**Issue by Delinquent-Pointer** [hbarton2/cscd350-f24-TeamNull#5]
### Scenario: List Classes
**Feature**: Listing All Classes and Contents

- **As a user**,  
  **I want to** list all my classes and their contents in an organized way,  
  **So that** I can review the structure of my project.

#### Steps:

1. **Given** that I am on the main page,  
   **When** I choose the option to save,  
   **Then** the class name, function name, and any other data I entered should be saved.

2. **Given** that I have typed the class name, field names, and method names,  
   **When** I choose the option to save in JSON,  
   **Then** all of this information should be saved in a JSON file format.

3. **Given** that I am on the main page,  
   **When** I choose the option to load from a file,  
   **Then** the JSON file should be loaded into my application.

4. **Given** that I start my application,  
   **Then** it should open in a CLI environment.

5. **Given** that I am on the main page,  
   **When** I choose the option to list classes,  
   **Then** all the classes and their contents should be displayed.

---

### Expected Time Estimate for These Tasks:
- **4-5 hours**: Includes coding, testing, and documenting the command-line interaction, saving/loading functionalities, and listing classes.

**Comment by danishwahidi** [comment]
Created a class that has one method to display the list of all UML Class with details.

**Comment by Delinquent-Pointer** [comment]
v1.1.58 has
