### ISSUE TITLE
Scenario: Add Field (ETE: 2-3 hours)

### ISSUE THREAD

**Issue by Delinquent-Pointer** [hbarton2/cscd350-f24-TeamNull#6]
# Scenarios and Features

### Scenario: Add Field
**Feature**: Add a Field to a Class

- **As a user**,  
  **I want to** add fields if they do not already exist,  
  **So that** I can update and add to the application.

#### Steps:
1. **Given** that I am in the menu,
2. **When** I select the option to add a field,
3. **Then** I should be required to input a valid class name,
4. **When** I enter a valid class name,
5. **Then** I should be required to input a unique field name,
6. **Then** I should be returned to the menu.

**Expected Time Estimate**: 2-3 hours

**Comment by sMooreEWU** [comment]
Added this feature in my pull request. Only real challenge left is ensuring name uniqueness.

**Comment by sMooreEWU** [comment]
Wrote it in Colton's new develop branch, still needs to be able to add a field
