### ISSUE TITLE
Scenario: Remove Field (ETE: 2-3 hours)

### ISSUE THREAD

**Issue by Delinquent-Pointer** [hbarton2/cscd350-f24-TeamNull#8]
### Scenario: Remove Field (ETE: 2-3 hours)
**Feature**: Remove a Field from a Class

- **As a user**,  
  **I want to** remove fields if they are present,  
  **So that** I can simplify and minimize my application.

#### Steps:
1. **Given** that I am in the menu,
2. **When** I select the option to remove a field,
3. **Then** I should be required to enter a valid class name,
4. **Given** that I have entered a valid class name,  
5. **Then** I should be required to enter a valid field name,
6. **Given** that the class name and field name exist,  
7. **Then** I should be returned to the menu.

**Comment by sMooreEWU** [comment]
Wrote the method for removing an existing field within a class. Just needs menu functionality.

**Comment by Delinquent-Pointer** [comment]
v1.1.60 addressed
