### ISSUE TITLE
Adds a parameter to a class that was already renamed

### ISSUE THREAD

**Issue by danishwahidi** [hbarton2/cscd350-f24-TeamNull#95]
![Bug In renaming a class](https://github.com/user-attachments/assets/df4e82ce-dca6-49ab-816e-7e4692be2893)

When I type a class name it saves it, I can add fields and methods to that class.
I can rename it , for example rename the class from Computer to Desktop.
Now, when I a parameter to Desktop, it shows that the parameter was added to both Computer and Desktop classes.

**Comment by Delinquent-Pointer** [comment]
might address this in Sprint 2 and documented issue
